### ISSUE TITLE
I met this error when run your cifar-10 train code.

### ISSUE THREAD

**Issue by bemoregt** [akanimax/pro_gan_pytorch#21]
Hi, @joebradly @joshalbrecht @akanimax @SaoYan 

I met this error when run your cifar-10 train code.

--
Files already downloaded and verified
Starting the training process ... 

Currently working on Depth:  0
Current resolution: 4 x 4

Epoch: 1
Traceback (most recent call last):
  File "depth4.py", line 61, in <module>
    batch_sizes=batch_sizes
  File "/home/oem/pro_gan_pytorch/pro_gan_pytorch/PRO_GAN.py", line 1046, in train
    labels, current_depth, alpha)
  File "/home/oem/pro_gan_pytorch/pro_gan_pytorch/PRO_GAN.py", line 865, in optimize_discriminator
    labels, depth, alpha)
  File "/home/oem/pro_gan_pytorch/pro_gan_pytorch/Losses.py", line 345, in dis_loss
    fake_out = self.dis(fake_samps, labels, height, alpha)
  File "/home/oem/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oem/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/oem/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/oem/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
  File "/home/oem/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/home/oem/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oem/pro_gan_pytorch/pro_gan_pytorch/PRO_GAN.py", line 305, in forward
    out = self.final_block(y, labels)
  File "/home/oem/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oem/pro_gan_pytorch/pro_gan_pytorch/CustomLayers.py", line 445, in forward
    labels = self.label_embedder(labels)  # [B x C]
  File "/home/oem/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oem/.local/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 110, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/oem/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1110, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: torch/csrc/autograd/variable.cpp:166: get_grad_fn: Assertion `output_nr_ == 0` failed.
--

What's wrong to me?

Thanks.

**Comment by akanimax** [comment]
Hi @bemoregt, sorry for late reply. This seems to be a pytorch's bug [link here](https://github.com/pytorch/pytorch/issues/7092). Could you please post the full code of your depth4.py file? And also try updating to the latest pytorch version?
Cheers :beers:!
@akanimax

**Comment by bemoregt** [comment]
Hi, @akanimax @joebradly @joshalbrecht @SaoYan 

My depth4.py file is here:

import torch as th
import torchvision as tv
import pro_gan_pytorch.PRO_GAN as pg

# select the device to be used for training
device = th.device("cuda" if th.cuda.is_available() else "cpu")
data_path = "cifar-10/"

def setup_data(download=False):
    """
    setup the CIFAR-10 dataset for training the CNN
    :param batch_size: batch_size for sgd
    :param num_workers: num_readers for data reading
    :param download: Boolean for whether to download the data
    :return: classes, trainloader, testloader => training and testing data loaders
    """
    # data setup:
    classes = ('plane', 'car', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck')

    transforms = tv.transforms.ToTensor()

    trainset = tv.datasets.CIFAR10(root=data_path,
                                   transform=transforms,
                                   download=download)

    testset = tv.datasets.CIFAR10(root=data_path,
                                  transform=transforms, train=False,
                                  download=False)

    return classes, trainset, testset


if __name__ == '__main__':

    # some parameters:
    depth = 4
    # hyper-parameters per depth (resolution)
    num_epochs = [10, 20, 20, 20]
    fade_ins = [50, 50, 50, 50]
    batch_sizes = [128, 128, 128, 128]
    latent_size = 128

    # get the data. Ignore the test data and their classes
    _, dataset, _ = setup_data(download=True)

    # ======================================================================
    # This line creates the PRO-GAN
    # ======================================================================
    pro_gan = pg.ConditionalProGAN(num_classes=10, depth=depth, 
                                   latent_size=latent_size, device=device)
    # ======================================================================

    # ======================================================================
    # This line trains the PRO-GAN
    # ======================================================================
    pro_gan.train(
        dataset=dataset,
        epochs=num_epochs,
        fade_in_percentage=fade_ins,
        batch_sizes=batch_sizes
    )
    # ====================================================================== 

Thanks.

**Comment by akanimax** [comment]
@bemoregt, Your code seems correct to me. Please try the following to update to latest pro_gan_pth package and latest Torch:
`pip install -U torch torchvision pro-gan-pth`
Let me know if this solves the problem :+1:

**Comment by arvindmvepa** [comment]
Hi @joebradly @joshalbrecht @akanimax @SaoYan, I'm getting the same error. I ran this from a jupyter notebook:
```
!pip install -U torch torchvision pro-gan-pth
import torch as th
import torchvision as tv
import pro_gan_pytorch.PRO_GAN as pg

# select the device to be used for training
device = th.device("cuda" if th.cuda.is_available() else "cpu")
data_path = "cifar-10/"

def setup_data(download=False):
    """
    setup the CIFAR-10 dataset for training the CNN
    :param batch_size: batch_size for sgd
    :param num_workers: num_readers for data reading
    :param download: Boolean for whether to download the data
    :return: classes, trainloader, testloader => training and testing data loaders
    """
    # data setup:
    classes = ('plane', 'car', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck')

    transforms = tv.transforms.ToTensor()

    trainset = tv.datasets.CIFAR10(root=data_path,
                                   transform=transforms,
                                   download=download)

    testset = tv.datasets.CIFAR10(root=data_path,
                                  transform=transforms, train=False,
                                  download=False)

    return classes, trainset, testset

# some parameters:
depth = 4
# hyper-parameters per depth (resolution)
num_epochs = [10, 20, 20, 20]
fade_ins = [50, 50, 50, 50]
batch_sizes = [128, 128, 128, 128]
latent_size = 128

# get the data. Ignore the test data and their classes
_, dataset, _ = setup_data(download=True)

# ======================================================================
# This line creates the PRO-GAN
# ======================================================================
pro_gan = pg.ConditionalProGAN(num_classes=10, depth=depth, 
                               latent_size=latent_size, device=device)
# ======================================================================

# ======================================================================
# This line trains the PRO-GAN
# ======================================================================
pro_gan.train(
    dataset=dataset,
    epochs=num_epochs,
    fade_in_percentage=fade_ins,
    batch_sizes=batch_sizes
)```
``` Files already downloaded and verified
Starting the training process ... 


Currently working on Depth:  0
Current resolution: 4 x 4

Epoch: 1
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-6272ded844a4> in <module>
     24     epochs=num_epochs,
     25     fade_in_percentage=fade_ins,
---> 26     batch_sizes=batch_sizes
     27 )

/usr/local/lib/python3.6/site-packages/pro_gan_pytorch/PRO_GAN.py in train(self, dataset, epochs, batch_sizes, fade_in_percentage, start_depth, num_workers, feedback_factor, log_dir, sample_dir, save_dir, checkpoint_factor)
   1044                     # optimize the discriminator:
   1045                     dis_loss = self.optimize_discriminator(gan_input, images,
-> 1046                                                            labels, current_depth, alpha)
   1047 
   1048                     # optimize the generator:

/usr/local/lib/python3.6/site-packages/pro_gan_pytorch/PRO_GAN.py in optimize_discriminator(self, noise, real_batch, labels, depth, alpha)
    863 
    864             loss = self.loss.dis_loss(real_samples, fake_samples,
--> 865                                       labels, depth, alpha)
    866 
    867             # optimize discriminator

/usr/local/lib/python3.6/site-packages/pro_gan_pytorch/Losses.py in dis_loss(self, real_samps, fake_samps, labels, height, alpha)
    343     def dis_loss(self, real_samps, fake_samps, labels, height, alpha):
    344         # define the (Wasserstein) loss
--> 345         fake_out = self.dis(fake_samps, labels, height, alpha)
    346         real_out = self.dis(real_samps, labels, height, alpha)
    347 

/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    141             return self.module(*inputs[0], **kwargs[0])
    142         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
--> 143         outputs = self.parallel_apply(replicas, inputs, kwargs)
    144         return self.gather(outputs, self.output_device)
    145 

/usr/local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py in parallel_apply(self, replicas, inputs, kwargs)
    151 
    152     def parallel_apply(self, replicas, inputs, kwargs):
--> 153         return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
    154 
    155     def gather(self, outputs, output_device):

/usr/local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py in parallel_apply(modules, inputs, kwargs_tup, devices)
     81         output = results[i]
     82         if isinstance(output, Exception):
---> 83             raise output
     84         outputs.append(output)
     85     return outputs

/usr/local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py in _worker(i, module, input, kwargs, device)
     57                 if not isinstance(input, (list, tuple)):
     58                     input = (input,)
---> 59                 output = module(*input, **kwargs)
     60             with lock:
     61                 results[i] = output

/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/site-packages/pro_gan_pytorch/PRO_GAN.py in forward(self, x, labels, height, alpha)
    303             y = self.rgb_to_features[0](x)
    304 
--> 305         out = self.final_block(y, labels)
    306 
    307         return out

/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/site-packages/pro_gan_pytorch/CustomLayers.py in forward(self, x, labels)
    443 
    444         # embed the labels
--> 445         labels = self.label_embedder(labels)  # [B x C]
    446 
    447         # compute the inner product with the label embeddings

/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/site-packages/torch/nn/modules/sparse.py in forward(self, input)
    116         return F.embedding(
    117             input, self.weight, self.padding_idx, self.max_norm,
--> 118             self.norm_type, self.scale_grad_by_freq, self.sparse)
    119 
    120     def extra_repr(self):

/usr/local/lib/python3.6/site-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   1452         # remove once script supports set_grad_enabled
   1453         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 1454     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   1455 
   1456 

RuntimeError: output_nr_ == 0 ASSERT FAILED at /pytorch/torch/csrc/autograd/variable.cpp:196, please report a bug to PyTorch.```

**Comment by akanimax** [comment]
@arvindmvepa, let me try to reproduce this error. Thanks for pointing out. BTW, are you running it on Collab?

**Comment by arvindmvepa** [comment]
@akanimax @joebradly @joshalbrecht @SaoYan No. Also it seems as if it is precisely this error: https://github.com/pytorch/pytorch/issues/14365

**Comment by arvindmvepa** [comment]
A temporary solution is discussed here: https://discuss.pytorch.org/t/normalizing-embeddings/7696/3. Though it's normalizing all the embedding vectors, rather than what max-norm does, which, to my understanding, only does this for vectors with norm greater than max-norm.

**Comment by akanimax** [comment]
@arvindmvepa,

Interesting. I am not sure if this impacts the performance in any way. The projectionGAN paper doesn't mention anything about the normalization of the embedding vectors. Can you try this out and check if it works? It would be great if you could open a PR with the max_norm change.

Best regards,
@akanimax

**Comment by arvindmvepa** [comment]
Sure (sorry for the long delay). Will do.

**Comment by guoyihonggyh** [comment]
Meet with the same error either. Has this been solved yet?

**Comment by arvindmvepa** [comment]
@joebradly @joshalbrecht @akanimax @SaoYan I made a PR if you all want to take a look

**Comment by akanimax** [comment]
closing due to inactivity.

**Comment by Mut1nyJD** [comment]
Well the example code in its current form definitely leads to a mode collaps pretty much straight away. When I removed max_norm=1 in nn.Embedding that's also what BigGAN does and change the default loss to hinge loss it seems to stays stable

**Comment by jyu-theartofml** [comment]
I had the same issue (pytorch 1.4, torchvision 0.5) trying to run conditionalProGan on multiple GPUs. I got the error `RuntimeError: diff_view_meta->output_nr_ == 0 INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579040055865/work/torch/csrc/autograd/variable.cpp:326, please report a bug to PyTorch
` And that went away when I removed max_norm=1 in nn.Embedding .

**Comment by akanimax** [comment]
Hello, @jyu-theartofml  and @Mut1nyJD,

I think I need to partake in this discussion. I guess, your comments are about the conditional version of ProGAN right? So, a couple of updates about that:

Not sure if you have noticed, but I am currently working on a major restructure/rewrite of the package for the [v3.0](https://github.com/akanimax/pro_gan_pytorch/pull/47) release and Following are two key points pertaining that:
1.) The conditional ProGAN is buggy at the moment and for the first release of 3.0, I won't be adding it. 
2.) I am guessing that the projection Discriminator is not well supported in PyTorch right now, so I might revert to the paper's ACGAN conditional version. If you have any experiments/services depending on the current api, please expect some major changes :smile:. 

Please feel free to peruse (skim lightly :wink:) the PR to get a head start.

Cheers :beers:!
@akanimax

**Comment by jyu-theartofml** [comment]
Thanks for the update! Conditional ProGan seems to be working and stable after I removed max_norm=1 in nn.Embedding.
